title: "Linda Mezzetti"
email: lindapaintsart@gmail.com
description: "Linda is an artist and sewist from Canada, now living in Melbourne, Australia"
baseurl: ""
# baseurl: "/lindamezzetti"
url: "http://lindamezzetti.com.au"
github_username:  "manicmike66"

theme: minima
plugins:
    - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries file path in the `include:` list.
#
exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
